#!/usr/bin/env python3
"""
Generate default kittenhats.ini with PIN 1234.
SHA-256(salt[16] || pin_ascii[4])
"""
import hashlib, os

salt = os.urandom(16)
pin = b'1234'
digest = hashlib.sha256(salt + pin).digest()

config = f"""; KittenHATS PIN Configuration
; Generated by gen_default_config.py
; Default PIN: 1234
; WARNING: Change this PIN before deploying!

[security]
pin_gate_enabled  = 1
pin_scheme        = sha256-salt-v1
pin_length        = 4
pin_salt_hex      = {salt.hex()}
pin_hash_hex      = {digest.hex()}
"""

print(config)
